### PR TITLE
Create gnublet.md

### PR DESCRIPTION
**Pull request by gnublet**
#### Related Issue

resolves # .
#### Credits

Paired with @github_handle

---

[Made at Fullstack LA](https://meetup.com/la-fullstack/events/234620974) :zap:

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Thank you @gnublet 

I had to tell you I used github.com's native Rebase button to squash your 2 commits into 1 and it's the best:

screen shot 2016-10-20 at 12 26 16 am

screen shot 2016-10-20 at 12 26 34 am

**Comment by gnublet** [comment]
Thanks for the pro tip!

**Comment by machikoyasuda** [comment]
@gnublet btw have you seen all the @maptimeLA repositories, projects & demos? there are some fun data sciencey projects in there: http://maptimela.github.io/about/ the d3/qgis/food pantry data one, for example. you might like it!!

**Comment by gnublet** [comment]
Yeah, this seems very interesting to me and I'll definitely check these out! Thank you!

**Pull request merged**
