### PR TITLE
Add links of coding resources for fsla meetup.

### PR DESCRIPTION
**Pull request by jaimemendozadev**
I'm working on the [fullstack.la](http://www.fullstack.la/) website with @kpearson. There's a [resources page](http://www.fullstack.la/resources) that's empty. I thought I'd get the ball rolling by creating a preliminary list of possible resources for publication and solicit advice/suggestions from everyone.

Please contribute as much or as little as you want. Final say on what gets published on the fullstack.la website is up to @kpearson & @machikoyasuda.

Enjoy. 😄 💻

### CODE REVIEW

**Comment by IanDCarroll** [comment]
For Python Docs: https://docs.python.org/3/
Also, for Vim: http://vim-adventures.com/  <==Seriously amazing.

**Comment by jaimemendozadev** [comment]
Awesomeness, keep 'em coming! And I think I'll add the open source projects links we ❤️. It's a rough draft.

**Comment by machikoyasuda** [comment]
LGTM 👍 ("Looks good to me")
What say you @kpearson? I'll leave the Merging to you!

**Comment by kpearson** [comment]
Fantastic! Merged. :facepunch:

**Comment by jaimemendozadev** [comment]
You're welki! 👊 😄

**Pull request merged**
