### PR TITLE
port local-meetups.md to .html for website usage

### PR DESCRIPTION
**Pull request by IanDCarroll**
I don't know if this is the way to go about this, but I figured "what the heck"...
I'm working on a static web page for meetups and that's what the html file is about.
If there's some much-easier/better way to go about this I'm all ears :ear: :smile: :ear:

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Were you able to open this "local-meetups.html" page on your computer? What does it look like there? Can you put a screenshot in your PR?

**Comment by IanDCarroll** [comment]
https://iandcarroll.github.io/FSLA/ Here it is as a thing.
screenshot from 2016-07-07 16 38 16

**Comment by machikoyasuda** [comment]
sweet!!

you can also open it by going to your browser and going to a URL like `file:///Users/ianscomputer/pairing-meetup/local-meedups.html`

**Comment by machikoyasuda** [comment]
or you can do this:
http://www.linuxjournal.com/content/tech-tip-really-simple-http-server-python

Open Terminal:
`$ cd /pairing-meetup
$ python -m SimpleHTTPServer`

and then open: `http://localhost:8000` in Chrome

**Comment by IanDCarroll** [comment]
I will try all those methods!

**Pull request merged**
