### PR TITLE
add ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by IanDCarroll**
#### Related Issue

#93 . (Not auto-closing because there is still one last file to be resolved)
#### Description

Add two markdown files:
1. ISSUE_TEMPLATE.md
2. PULL_REQUESTS_TEMPLATE.md
#### Screenshots (if appropriate):

issue_template
pull_request
#### Context and Reason Why

These two files will be used to copy-paste pull requests to other sites. This does 3 things that are awesome:
1. It means that pull requests from FullStack LA will be of a consistent higher quality.
2. It means we'll be more able to account for all the awesome contributions our group makes.
3. It means that when submitting issues to this repository, these templates will auto-generate.

This will allow us to eventually generate pages that display our contributions at a glance, and who knows what else. (Also, I used the template proposed for submitting this pull request.)
#### How Has This Been Tested?

It has not been very well tested! Although it is basically markdown.
It still needs to be seen whether GitHub will hook these files and auto-generate issue and pull request templates for master.
It has been proofread, but could always use a few more eyes.
Let me know if there's any changes in wording or anything else. I tried to keep it natural and without too many extras.
#### Credits

@IanDCarroll - Dev - working solo 
@machikoyasuda  - Product Owner

---

[Made at Fullstack LA](https://meetup.com/la-fullstack/events/234620974) :zap:

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Yay!

Can you add 1 more thing: 
`Paired with @github_handle` of you who you paired with.

**Comment by IanDCarroll** [comment]
Maybe I need to make it bigger, but actually the credits section asks for this in comments. I'll make it more explicit. 

Also: there's a typo! 

AlsoAlso: Added PULL_REQUEST_EXAMPLES.md as well. Is that enough? or do you need it more fancy?)

**Comment by IanDCarroll** [comment]
How's that looking now?

**Comment by machikoyasuda** [comment]
It's a good start for now! Yippeee for getting us started on this 👍

**Comment by machikoyasuda** [comment]
@IanDCarroll look at this:

https://github.com/fullstackla/pairing-meetup/issues/new

This is how it looks!!

**Comment by IanDCarroll** [comment]
pretty sick!

**Pull request merged**
