### PR TITLE
Delete target='blank' attribute from links

### PR DESCRIPTION
**Pull request by jaimemendozadev**
No problem @machikoyasuda! Fixed as requested! Let me know if I need to do something else. 😄

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Oh now we have a merge conflict :)

We can practice resolving merge conflicts in Atom and command line at the next Fullstack. cc @kpearson

**Comment by jaimemendozadev** [comment]
@machikoyasuda @kpearson Did I fix it? I really really hope I resolved it on my own. Fingers crossed. 🙏

**Comment by machikoyasuda** [comment]
@jaimemendozadev YES!!!!

**Comment by machikoyasuda** [comment]
@jaimemendozadev Merge Conflict resolved ⭐

**Pull request merged**
